name = "homework-api"
main = "src/index.js"
compatibility_date = "2024-05-01"

[[d1_databases]]
binding = "DB"
database_name = "REPLACE_WITH_DATABASE_NAME"
database_id = "REPLACE_WITH_DATABASE_ID"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "REPLACE_WITH_PROD_BUCKET"
preview_bucket_name = "REPLACE_WITH_PREVIEW_BUCKET"

[vars]
# Optional admin token if you want to gate DELETE endpoints
# ADMIN_TOKEN = "set-this-to-your-admin-token"

[ai]
binding = "AI"

[dev]
port = 8789
