name = "homework-api"
main = "src/index.js"
compatibility_date = "2024-05-01"

[[d1_databases]]
binding = "DB"
database_name = "homework-db"
database_id = "9e6ffe54-c396-4f82-ae0c-36b1e784618b"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "homework"
preview_bucket_name = "homework"

[vars]
ADMIN_TOKEN = "bagelbar"

[ai]
binding = "AI"

[dev]
port = 8789
