name = "reading-api"
main = "src/index.js"
compatibility_date = "2024-05-01"

[[d1_databases]]
binding = "DB"
database_name = "reading_goals"
database_id = "134b7f1d-5ecc-4a29-a1e6-123a4fd9d80d"

[[r2_buckets]]
binding = "PHOTOS"
bucket_name = "reading-photos"
preview_bucket_name = "reading-photos"

[[kv_namespaces]]
binding = "AGG_KV"
id = "e19b11b1e868415092f3345fdcc5831d"
preview_id = "e19b11b1e868415092f3345fdcc5831d"

[vars]
ADMIN_TOKEN = "bagelbar"

[dev]
port = 8788
